### ISSUE TITLE
MSVC x64 Windows compile error C2065: 'tinyco_msvc_x64_entry': undeclared identifier

### ISSUE THREAD

**Issue by ddengster** [soundsrc/tinycoroutine#1]
Hey, like what you've got here. 

It seems that x64 windows isnt accounted for as a compile target. What would it take to get it working?

**Comment by ddengster** [comment]
Also, after some custom fixes I hit crashes on msvc release mode x64, caused by /O2. Switching to /Od helped, some I would assume there's some optimization with the stack that causes this. Any help for this issue would be appreciated :)

**Comment by soundsrc** [comment]
Thanks letting me know about the issues. It's been 5 years since I've touch this bit of code. The X64 platform is a bit tricky with the setjmp()/longjmp() as there some strange magic that happens with those on the X64. In any case, I installed VS2017 and tried it out with /O2 and ended up identifying an existing bug. I spent a bit of time and patched up a few things in the master branch. Happy New Years!
